# This is a basic workflow to help you get started with Actions

name: ci/cd-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.14.2 
          
      - name: packaging lambda app 
        run: | 
             npm install 

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: dist
     
     
     # This workflow contains a single job called "build"
  test:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - uses: actions/download-artifact@master
      #   with:
      #     name: my-artifact
      #     path: dist
      # building packages 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: func.zip
          path: dist
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.14.2 
          
      - name: test lambda app 
        run: | 
             npm install 
             npm run test
             npm prune --production

  deploy:
    needs: test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.2.1

      # - uses: actions/download-artifact@master
      #   with:
      #     name: my-artifact
      #     path: dist

      - name: provision Lambda
        run: | 
              cd terraform 
              terraform init
              export TF_VAR_access_key="${{secrets.ACCESS_KEY}}"
              export TF_VAR_secret_key="${{secrets.SECRET_KEY}}"
              terraform apply --auto-approve
              sleep 10
              terraform destroy --auto-approve 
                
        
          
        
